pom.groupId=ca.rmen
pom.version=0.0.4
pom.description=Port of GnuCOBOL for kmp.
pom.vcsUrl=https://github.com/caarmen/cobol-mobile
pom.developer=Carmen Alvarez
pom.license=LGPLv3
java.compatibility=11
kotlin.compatibility=2.4.0
kdoc.projects=:gnucobol-kmp