{
  "formatVersion": "1.1",
  "component": {
    "url": "../../gnucobol-kmp/0.0.4/gnucobol-kmp-0.0.4.module",
    "group": "ca.rmen",
    "module": "gnucobol-kmp",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gnucobol-kmp-iosArm64Main-0.0.4.klib",
          "url": "gnucobol-kmp-iosarm64-0.0.4.klib",
          "size": 4473,
          "sha512": "9c9458e64efa70f3cca4d9d2534ea5dbb9c3bcfcb53600bf27a474afa19e0cfb49d4304b100080aff528ff00fe815d33ed77ee0c5ef1ea415e83759b3bbe43cc",
          "sha256": "f93c1943dbb1ecbfc8d9dd9944ad1e091c809ca20a073d0003a91ac0b7c05dd2",
          "sha1": "7a9115da4fa84479f2b5dafc3aac4408e412827f",
          "md5": "e53dfe8cec45b429fdc3e9a2197a9ef9"
        },
        {
          "name": "gnucobol-kmp-iosArm64Cinterop-gnuCobolMain-0.0.4.klib",
          "url": "gnucobol-kmp-iosarm64-0.0.4-cinterop-gnuCobol.klib",
          "size": 5198,
          "sha512": "465174dfdd4b4548affda75dd75f6288093147df595a1dcab8571aa221c725e37d123abcb993229d2def3a41840a0a926dab4d957dc685db082f2e10e9e836dd",
          "sha256": "889ea790d2b2fb454e23b103df63c5b43089487deb890b245326bb1b8c9f2934",
          "sha1": "c8347cccfd920daa3b0b5c4487d6914d06330f81",
          "md5": "97fc4611113a8557587166aaf5ce3e51"
        },
        {
          "name": "gnucobol-kmp-iosArm64Cinterop-swiftPMImportMain-0.0.4.klib",
          "url": "gnucobol-kmp-iosarm64-0.0.4-cinterop-swiftPMImport.klib",
          "size": 5770,
          "sha512": "c38c9510bee66ae7198f97b9d0ddfc89317752485a838bc40d97c5dc975a7baadf60b5a96137eb243004109ed97723f9c3ca6be2abfc77beb40a652563fa62e8",
          "sha256": "c40a2b3520f4a19616498e24ed26f0ba3065c4ea6cea2e487e9b7685127fd0d0",
          "sha1": "063a54d256b2f91bae6b32969e6086182b576b4c",
          "md5": "498c86723f2f84cdcc124ec173d431af"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "gnucobol-kmp-iosarm64-0.0.4-sources.jar",
          "url": "gnucobol-kmp-iosarm64-0.0.4-sources.jar",
          "size": 650,
          "sha512": "b5e711b51859bb3b816c3339b73436c0fe6f0ea8b4a2b3187631ed9c7bcb1d9757830173214100f5a22607999743738a512ba8d3f8aca761cefd5d4dc1dff229",
          "sha256": "e2ff6bd3cbedd38227dbcb334249c78e021d970fa811c50100939bebbd0d002a",
          "sha1": "976aab3bb8b805938914fe06169e643171c3a227",
          "md5": "40dcca783d1890ae6101e23afca4aef3"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gnucobol-kmp-iosarm64-0.0.4-metadata.jar",
          "url": "gnucobol-kmp-iosarm64-0.0.4-metadata.jar",
          "size": 28198,
          "sha512": "481ac06b4dad8f704979d60e2d9576ecd9289216b33114cc73533348013591630cf85ac6f57ebcc5ad5ca55ec1cd5e7e8984cb70800b6e03ac88bbe9ebd5e5ae",
          "sha256": "92ae5c1d7ad3b33961c517d6ed0cb5bbb76b6af9a1bfcf85f43f87786faf08db",
          "sha1": "dd6da1eea711dda7ef1c56ac19fd83c6513921fe",
          "md5": "d817642993679b49af7db11e815b13a7"
        }
      ]
    }
  ]
}
